import { type FormEvent, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { useAgent } from "agents/react";
import { useAgentChat } from "@cloudflare/ai-chat/react";
import ReactMarkdown from "react-markdown";
import { accounts, money, type Investigation } from "./billing";
import type { LedgerLensState } from "./server";
import "./styles.css";

const demoEmail = "demo@ledgerlens.local";
const demoPassword = "ledgerlens-demo";

function Login({ onLogin }: { onLogin: () => void }) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState("");
  function submit(event: FormEvent) { event.preventDefault(); if (email === demoEmail && password === demoPassword) onLogin(); else setError("Use the demo credentials shown below."); }
  return <main className="login-shell"><form className="login-card" onSubmit={submit}><p className="eyebrow">Fictional support workspace</p><h1>LedgerLens</h1><p>Sign in to review read-only billing investigations.</p><label>Email<input aria-label="Email" value={email} onChange={(e) => setEmail(e.target.value)} /></label><label>Password<input aria-label="Password" type="password" value={password} onChange={(e) => setPassword(e.target.value)} /></label>{error && <p className="error">{error}</p>}<button>Sign in</button><p className="demo-creds">Demo only<br /><code>{demoEmail}</code><br /><code>{demoPassword}</code></p></form></main>;
}
function InvestigationPanel({ state }: { state?: LedgerLensState }) { const result = state?.investigation as Investigation | undefined; if (state?.status === "investigating") return <aside className="panel"><h2>Investigation</h2><p className="status">Finding account-scoped evidence…</p></aside>; if (!result) return <aside className="panel"><h2>Investigation</h2><p>Select one account and two of its invoices to begin.</p></aside>; return <aside className="panel"><h2>Evidence-backed result</h2><p className="variance">{money(result.currentInvoiceCents)} <span>vs.</span> {money(result.priorInvoiceCents)}</p><p>Difference: <strong>{money(result.changeCents)}</strong></p><h3>Evidence</h3><ul>{result.evidence.map((item) => <li key={item.id}><code>{item.id}</code><strong>{item.label}</strong><span>{item.note}</span></li>)}</ul><h3>Customer-ready draft</h3><div className="draft"><ReactMarkdown>{state?.customerDraft}</ReactMarkdown></div><p className="review">Human review required before sending.</p></aside>; }
function Workspace() {
  const [accountId, setAccountId] = useState(accounts[0].id); const account = useMemo(() => accounts.find((item) => item.id === accountId)!, [accountId]);
  const [priorId, setPriorId] = useState(account.invoices[0].id); const [currentId, setCurrentId] = useState(account.invoices[1].id); const [input, setInput] = useState("Explain the difference and draft a reply I can send.");
  const agent = useAgent<LedgerLensState>({ agent: "LedgerLensAgent", name: `support-demo-${accountId}` }); const { messages, sendMessage, status } = useAgentChat({ agent }); const busy = status !== "ready";
  function chooseAccount(id: string) { const next = accounts.find((item) => item.id === id)!; setAccountId(id); setPriorId(next.invoices[0].id); setCurrentId(next.invoices[1].id); }
  function submit(event: FormEvent) { event.preventDefault(); if (busy || priorId === currentId) return; const prior = account.invoices.find((item) => item.id === priorId)!; const current = account.invoices.find((item) => item.id === currentId)!; sendMessage({ text: `Account: ${account.name} (accountId: ${account.id}). Compare baseline ${prior.id} (${prior.period}) against ${current.id} (${current.period}). ${input}` }); setInput(""); }
  const state = agent.state; const completed = state?.status === "complete" && state.customerDraft;
  return <main className="workspace"><aside className="accounts"><p className="eyebrow">Support agent · demo only</p><h1>LedgerLens</h1><p className="muted">Each account has its own persisted chat session and invoice scope.</p><h2>Accounts</h2>{accounts.map((item) => <button className={`account ${item.id === accountId ? "selected" : ""}`} key={item.id} onClick={() => chooseAccount(item.id)}><strong>{item.name}</strong><span>{item.industry} · {item.invoices.length} invoices</span></button>)}</aside><section className="chat"><header><p className="eyebrow">{account.name} · fictional demo</p><h2>Compare invoices</h2><div className="invoice-picker"><label>Baseline invoice<select aria-label="Baseline invoice" value={priorId} onChange={(e) => setPriorId(e.target.value)}>{account.invoices.map((invoice) => <option key={invoice.id} value={invoice.id}>{invoice.period} · {money(invoice.totalCents)}</option>)}</select></label><label>Comparison invoice<select aria-label="Comparison invoice" value={currentId} onChange={(e) => setCurrentId(e.target.value)}>{account.invoices.map((invoice) => <option key={invoice.id} value={invoice.id}>{invoice.period} · {money(invoice.totalCents)}</option>)}</select></label></div>{priorId === currentId && <p className="error">Choose two different invoices.</p>}</header><div className="messages" aria-live="polite">{messages.length === 0 && <p className="empty">Ask LedgerLens to explain the selected account’s invoice difference.</p>}{messages.map((message) => <article key={message.id} className={`message ${message.role}`}><span>{message.role === "user" ? "Support agent" : "LedgerLens"}</span>{message.parts.map((part, index) => part.type === "text" ? <p key={index}>{part.text}</p> : null)}</article>)}{completed && <article className="message assistant completion"><span>LedgerLens · completed investigation</span><p><strong>Evidence-backed comparison is ready in the detail panel.</strong></p><ReactMarkdown>{state.customerDraft}</ReactMarkdown><button className="copy" type="button" onClick={() => navigator.clipboard.writeText(state.customerDraft ?? "")}>Copy draft</button><p className="review">Human review required before sending.</p></article>}</div><form onSubmit={submit}><textarea value={input} onChange={(e) => setInput(e.target.value)} aria-label="Billing question" rows={3} /><button disabled={busy || priorId === currentId}>{busy ? "Investigating…" : "Investigate"}</button></form></section><InvestigationPanel state={state} /></main>;
}
function App() { const [signedIn, setSignedIn] = useState(false); return signedIn ? <Workspace /> : <Login onLogin={() => setSignedIn(true)} />; }
createRoot(document.getElementById("root")!).render(<App />);
